services:
  traefik:
    image: traefik:v2.9.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "88:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cryobiobank-api:
    build:
      context: ../cryobiobank-api
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=cryobiobank-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psql
      - DB_NAME=postgres
      - DB_PREFIX=postgresql
      - KEYCLOAK_UI_ID=${KEYCLOAK_UI_ID}
      - KEYCLOAK_API_ID=${KEYCLOAK_API_ID}
      - KEYCLOAK_API_SECRET=${KEYCLOAK_API_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - APP_NAME=${APP_NAME}
      - DEPLOYMENT=local
    ports:
      - 3005:3000
    depends_on:
        - cryobiobank-db
    volumes:
      - ../cryobiobank-api/src:/app/src
      - cryobiobank-api-build-data:/app/target  # Store builds in docker volume
      - ../cryobiobank-api/Cargo.toml:/app/Cargo.toml
      - ../cryobiobank-api/Cargo.lock:/app/Cargo.lock
      - ../kubeconfig:/root/.kube/config.yaml
    labels:
      - "traefik.http.routers.cryobiobank-api.rule=Host(`cryobiobank`) && PathPrefix(`/api`)"
      - "traefik.http.services.cryobiobank-api.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 3

  cryobiobank:
    build:
      context: .
      dockerfile: Dockerfile.dev
    labels:
      - "traefik.http.routers.cryobiobank.rule=Host(`cryobiobank`)"
      - "traefik.http.services.cryobiobank.loadbalancer.server.port=5173"
    volumes:
      - ../cryobiobank-ui:/app
#      - ../cryobiobank-ui/node_modules:/app/node_modules

  cryobiobank-db:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=postgres
    ports:
      - 5443:5432
    volumes:
      - cryobiobank-db-data:/var/lib/postgresql/data


  # cryobiobank-test-db:
  #   image: postgis/postgis:17-3.5
  #   container_name: cryobiobank-test-db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=psql
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5444:5432"

  # cryobiobank-test-api:
  #   build:
  #     context: ../cryobiobank-api
  #     dockerfile: Dockerfile.test
  #   container_name: cryobiobank-test-api
  #   depends_on:
  #     - cryobiobank-test-db
  #   environment:
  #     - DB_HOST=cryobiobank-test-db
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=psql
  #     - DB_NAME=postgres
  #     - DB_PREFIX=postgresql
  #     - KEYCLOAK_URL=http://fake-url-for-tests
  #     - KEYCLOAK_REALM=test
  #     - KEYCLOAK_UI_ID=test
  #     - KEYCLOAK_API_ID=test
  #     - KEYCLOAK_API_SECRET=test
  #     - APP_NAME=cryobiobank-api-tests
  #     - DEPLOYMENT=test
  #   volumes:
  #     - ../cryobiobank-api:/app
      
volumes:
  cryobiobank-db-data:
  cryobiobank-api-build-data:
